
public enum HTTPError {
	Bad_Request,Unauthorized,Payment_Required,Forbidden ,Not_Found ,Method_Not_Allowed,Not_Acceptable,Proxy_Authentication_Required,Request_Timeout,
	Conflict,Gone,Length_Required,Precondition_Failed,Request_Entity_Too_Large,Request_URI_Too_Long,
	Unsupported_Media_Type,Requested_Range_Not_Satisfiable,Expectation_Failed,Im_a_teapot,Authentication_Timeout,Method_Failure,Unprocessable_Entity,Locked;
}
